version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: guest-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: guest_service
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - guest-network

  guest-service:
    build: .
    container_name: guest-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/guest_service?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - guest-network

volumes:
  mysql_data:

networks:
  guest-network:
    driver: bridge